config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "u/:username" => "public#profile", as: :profile

  resources :communities do
    resources :posts
  end
  resources :subscriptions
  resources :comments, only: [:create]

 
  root to: "public#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    validates_presence_of :message, :user_id ,:post_id
end
    

app/models/community.rb
class Community < ApplicationRecord
    validates_presence_of  :name, :rules
    belongs_to :user
    has_many :subscriptions
    has_many :subscribers, through: :subscriptions, source: :user
    has_many :posts
   
   
  end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :body, :user_id, :community_id

    belongs_to :community
    belongs_to :user
    has_many :comments
    
   def score
    1
   end
  end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :community
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :communities, through: :subscriptions
  has_many :posts
  has_many :comments
  validates_presence_of :username, :first_name, :last_name

  def full_name
#    current_user.first_name +current_user.last_name
    "#{first_name}  #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update , keys: [:first_name,:last_name, :username])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:username])
    end
  end
  

app/controllers/comments_controller.rb
class CommentsController <  ApplicationController
    def create
    @comment = Comment.new comment_params
    @comment.user_id =current_user.id

        respond_to do |format|
            format.js{
            if @comment.save
                @comments = Comment.where(post_id: @comment.post_id)
                render "comments/create"
            else
                #unable to save
            end
        }
        end

    end

    private
    def comment_params
            params.require(:comment).permit(:message, :post_id)
    end
   
end

app/controllers/communities_controller.rb
class CommunitiesController <  ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_community, only: [:show]

    def index
        @communities =Community.all
    end

    def new
        @community =Community.new
    end

    def create
        @community =Community.new(community_params)
        @community.user_id =current_user.id
        if @community.save
          redirect_to @community
        else
          render :new
        end

    end

    def show
       
       @posts = @community.posts
       @subscribers_count = @community.subscribers.count
       @is_subscribed= user_signed_in? ? Subscription.where(community_id: @community.id, user_id: current_user.id ).any? : false 
       @subscription = Subscription.new  
    end

    private
    def set_community
      @community = Community.find(params[:id])
    end
    def community_params
        params.require(:community).permit(:name, :url,:rules, :summary)
      end
end

app/controllers/posts_controller.rb
class PostsController <  ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_post, only: [:show]
    before_action :auth_subscriber, only: [:new]
    def index
        @posts =Post.all
    end
    
    def show 
        @comment =Comment.new
        
    end 

   

    def new
        @community= Community.find(params[:community_id])
        @post =Post.new
    end

    def create
        @post =Post.new(post_params)
        @post.user_id =current_user.id
        @post.community_id = params[:community_id]
        if @post.save
          redirect_to community_path(@post.community_id)
        else
            @post.community_id = params[:community_id]
            render :new
        end

    end

    private
    def post_params
        params.require(:post).permit(:title,:body)
    end
    def set_post
        @post = Post.includes(:comments).find(params[:id])
    end
    def auth_subscriber
      unless Subscription.where(community_id: params[:community_id], user_id: current_user.id ).any?  
      redirect_to root_path , flash: {danger: "You are not authorized to view this page"}
      end
    end

end

app/controllers/public_controller.rb
class PublicController <  ApplicationController
    def index
        @communities =Community.all
        @posts= Post.order(id: :desc).limit(20)
    end
    def profile
        @profile = User.find_by_username(params[:username])
        @posts = @profile.posts
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController <  ApplicationController
    def create
        @subscription =Subscription.new(subscription_params)
        @subscription.user_id = current_user.id
        @subscription.save
        redirect_to community_path(@subscription.community_id)
    end
    def subscription_params
        params.require(:subscription).permit(:community_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
console.log("comment created.. ");
document.getElementById("post-comments").innerHTML = "<%= escape_javascript(render partial: 'posts/comments', locals: { comments: @comments }) %>";

app/views/communities/_form.html.erb
<div class="row ">
    <div class="col-sm-6 ">

        <%= form_for @community do |c| %>
        <div class="form-group">
        <%= label_tag :name%>
        <%= c.text_field :name, class:"form-control"%>

       

        <%= label_tag :rules%>
        <%= c.text_area :rules, class:"form-control"%>
        
         <%= label_tag :summary%>
        <%= c.text_field :summary, class:"form-control"%>
        </div>
        <%= submit_tag "Submit", class: "btn btn-primary mt-3"%>
        <% end %>
    </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id%>
    <%= f.submit "Join community", class: "btn btn-success text-uppercase float-end"%>
<% end %>

app/views/communities/index.html.erb
<%if user_signed_in?%>

<div class="float-end mt-4">
    <%= link_to "Create new community", new_community_path, class: "btn btn-primary"%>
</div>
<%end%>
    <div class="mt-4 col-9">
        <% if @communities.size > 0%>

        <% @communities.each do |community|%>
        <div class="card p-3">

            <h3> <%= link_to community.name,  community %></h3>
            <%= simple_format community.summary%>

           <small> <%=  simple_format community.rules%></small>

        </div>
        <br/>

        <%end%>

        <%else%>
        <p>Nothing here</p>
        <% end %>
    </div>

app/views/communities/new.html.erb
<h2>New community</h2>
<%= render partial: "form" %>

app/views/communities/show.html.erb
         
<div class="row mb-3">
    <div class="col-sm-8">
        <h3><%= @community.name%></h3>
    </div>
    <div class="col-sm-4 ">
    <% if @is_subscribed%>
        <%= link_to "Create new post", new_community_post_path(@community),class:"btn btn-primary mt-4 float-end"%>
    <% else %>
        <%= render partial: "communities/subscribe", locals: {community_id: @community.id}%>

    <%end%>

    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        <%= render partial: "posts/list", locals: {posts: @posts}%>
    </div>
    <div class="col-sm-4">
        <div class="card p-3">
            <p class="h5">About this community </p>
            <p><%= @community.summary%></p>
            <p> <%= pluralize @subscribers_count,"member"%></p>
                <small>
                    <Strong>Rules</Strong>
                    <%= simple_format @community.rules%>
                </small>
        </div>
    </div>
    
</div>
           
    
   
    

app/views/layouts/_footer.html.erb
<footer>
footer
</footer>

app/views/layouts/_header.html.erb
  <div class="row">
    <div class="col-12 pt-3 pb-3">

          <div class="float-end">
             <% if user_signed_in? %>
              <div class="btn-group" role="group" aria-label="smth">
                <%= link_to  current_user.full_name  , profile_path(current_user.username), class: "dropdown-item h5" %>
                <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item h5" %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item h5" %>
              </div> 
          </div>
          
          <% else %>
          <div class="float-end">
             
              <div class="btn-group" role="group" aria-label="smth">
        
                <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
              </div> 
          </div> 
          </div> 
                 
          
         
         
         
          
          <% end %>
          <p class="h3 "><%= link_to "My Community", root_path %></p>
         
         </div> 

    </div> 
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCommunity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">

        <%= render "layouts/header" %>

  <section class= "bg-light">
  <div class="col-sm-12 pt-4">
  <div class="container">
        <%= yield %>
      </div>
      </div>
       
  </section>
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment|%>
<div class="comment">
    <%= link_to comment.user.full_name, profile_path(comment.user.username) %>
    <%= simple_format comment.message%>
</div>
<%end%>

app/views/posts/_form.html.erb
<div class="row ">
    <div class="col-sm-6 ">

        <%= form_for [@community,@post] do |c| %>
        <div class="form-group">
        <%= label_tag :title%>
        <%= c.text_field :title, class:"form-control"%>

        <%= label_tag :body%>
        <%= c.text_area :body, class:"form-control"%>


        </div>
        <%= submit_tag "Submit", class: "btn btn-primary mt-3"%>
        <% end %>
    </div>
</div>

app/views/posts/_list.html.erb
<% @posts.each do |post|%>
    <div class="card mt p-3 mb-3">
        <div class=" row ">
            <div class=" col-11">
                <h2><%= link_to post.title, community_post_path(post.community_id, post)%></h2>
                <small><%=link_to post.community.name ,community_path(post.community) %> posted by <%= link_to post.user.full_name, profile_path(post.user.username) %>  <%=time_ago_in_words post.created_at%> ago.</small>
                <p class="mt-4"><%= truncate post.body, length: 200 %></p>
            </div>
        </div>    
    </div>
    
<%end%>

app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New post </h2>
<%= render partial: "form" %>

app/views/posts/show.html.erb
<h2><%= @post.title%></h2>

<%= simple_format @post.body%>
<div id="post-comments">

<%= render partial: "posts/comments", locals: {comments: @post.comments}%>
</div>
<h5>Please leave a comment</h5>
<%= form_for @comment,remote: true  do |f|%>
<%= f.hidden_field :post_id, value: @post.id%>
<%= f.text_area :message, placeholder: "Your comment goes here", class: "form-control" %>
<%= f.submit "Submit comment",class: "btn btn-success mt-2"%>
<%end %>